### ISSUE TITLE
Button truncate on android

### ISSUE THREAD

**Issue by alex-maxime** [alex-melnyk/Tabber#1]
Hello,

I have tested on android, but this is what i have. 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/3592127/41462903-bdaa33ca-7094-11e8-92d7-bce3c73eb294.png">

The button is tunked,

Do you have any idea why ?

Any support is welcome.

**Comment by tiann** [comment]
overflow visible doesn't work on Android: https://github.com/facebook/react-native/issues/6802

**Comment by alex-melnyk** [comment]
@tiann it works but with hacks))

@Alex237 did you check the [Overflow Fixed](https://github.com/alex-melnyk/Tabber/tree/overflow_fixed) branch?
