### ISSUE TITLE
Height of bottom bar SafeAreaView

### ISSUE THREAD

**Issue by batkov** [alex-melnyk/Tabber#10]
Hi,

Working on TabBar. Tried your example and faced issue with iPhone X.

There is explicit state in MultiBar.js that we cannot change height of background.
`<View style={{ height: 49 }}/>`

However, it appears to corrupt UI on iPhone X. Can you advise?

![Screen Shot 2019-09-12 at 12 25 07 PM](https://user-images.githubusercontent.com/582671/64771890-6469bb80-d558-11e9-931d-ee6793d0c676.png)

**Comment by alex-melnyk** [comment]
So maybe we need to put there condition or add prop value. If you can build PR please do it

**Comment by Scbojer** [comment]
I've managed this by importing SafeAreaView from 'react-navigation' opposed to 'react-native'

![image](https://user-images.githubusercontent.com/7848756/66043128-a3b77680-e51e-11e9-9c3b-d871f2307884.png)

**Comment by ramazanarslan** [comment]
> Hi,
> 
> Working on TabBar. Tried your example and faced issue with iPhone X.
> 
> There is explicit state in MultiBar.js that we cannot change height of background.
> `<View style={{ height: 49 }}/>`
> 
> However, it appears to corrupt UI on iPhone X. Can you advise?
> 
> ![Screen Shot 2019-09-12 at 12 25 07 PM](https://user-images.githubusercontent.com/582671/64771890-6469bb80-d558-11e9-931d-ee6793d0c676.png)

hi, Did you solve this problem?
