### ISSUE TITLE
Error on "react-navigation": "^2.5.5"

### ISSUE THREAD

**Issue by lntoan** [alex-melnyk/Tabber#6]
Hi Alex

I tested your project with "react-navigation": "^2.5.5" and It has error.

**Comment by alex-melnyk** [comment]
Good, I tested it with "react-navigation": "^3.0.8" as it's described in package.json and it works well.

**Comment by lntoan** [comment]
Could you fix for "react-navigation" 2.x.x?

**Comment by alex-melnyk** [comment]
Sure, if you will provide more details about your error ;-)
1. Information about your phone (Brand, Model, Android version, etc.)
2. Package.json, an example of your implementation, etc.
3. Error screen, (logs, etc.)
4. Your opinion (some recommendations or maybe you something noticed)
_Also please notice that this repo **just example** of using https://github.com/alex-melnyk/react-native-multibar module, so if your error related to that library please open issue directly in the module repo._
