### ISSUE TITLE
Draggable tab

### ISSUE THREAD

**Issue by alisherakb** [alex-melnyk/Tabber#7]
First of all, THANKS for an amazing example!

Can you assist me in making a draggable tab? So that on dragging to certain x,y it opens another screen? 
I'm trying to use `react-native-interactable` inside `<AddButton />` screen  (Medium post v1), but my button remains static.

Here is the code of `<AddButton />` page:

```
import React, { Component } from "react";
import { Animated, TouchableHighlight, View, StyleSheet } from "react-native";
import Interactable from "react-native-interactable";

class AddButton extends Component {
  render() {
    return (
      <Animated.View style={styles.container}>
        <Interactable.View
          snapPoints={[{ x: 0, y: 72 }, { x: 0, y: 250 }]}
          initialPosition={{ x: 0, y: 250 }}
        >
          <Animated.View
            style={{
              position: "absolute",
              width: 96,
              height: 96,
              backgroundColor: "#EE2C38",
              borderRadius: 48
            }}
          />
        </Interactable.View>
      </Animated.View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    position: "absolute",
    alignItems: "center",
    backgroundColor: "red",
    width: 96,
    height: 96,
    borderRadius: 48
  }
});

export { AddButton };

``` 

Desired behaviour:
<img width="612" alt="screenshot 2019-03-01 at 8 54 55 pm" src="https://user-images.githubusercontent.com/26904008/53661296-af7d4a80-3c68-11e9-9f80-73f84529aada.png">
<img width="384" alt="screenshot 2019-03-01 at 8 55 56 pm" src="https://user-images.githubusercontent.com/26904008/53661302-b1470e00-3c68-11e9-9442-aafc719d33a5.png">

**Comment by alex-melnyk** [comment]
Hi, to do that you need to wrap button.
`MultiBar: {
        screen: () => null,
        navigationOptions: ({navigation}) => ({
            tabBarIcon: () => (
                <View style={{
                    flex: 1
                }}>
                    <Interactable.View
                        snapPoints={[{x: 0, y: 0}]}
                        onSnap={() => {
                        }}>
                        <MultiBarToggle
                            navigation={navigation}
                            actionSize={30}
                            routes={[
                                {
                                    routeName: Routes.OtherScreen,
                                    color: '#FF8360',
                                    icon: (
                                        <Icon
                                            name="rocket"
                                            color="#333333"
                                            size={15}
                                        />
                                    )
                                },
                                {
                                    routeName: Routes.OtherScreen,
                                    color: '#E8E288',
                                    icon: (
                                        <Icon
                                            name="dashboard"
                                            color="#333333"
                                            size={15}
                                        />
                                    )
                                },
                                {
                                    routeName: Routes.OtherScreen,
                                    color: '#7DCE82',
                                    icon: (
                                        <Icon
                                            name="gears"
                                            color="#333333"
                                            size={15}
                                        />
                                    )
                                },
                            ]}
                            icon={(
                                <Icon
                                    name="plus"
                                    color="#FFFFFF"
                                    size={24}
                                />
                            )}
                        />
                    </Interactable.View>
                </View>
            )
        }),
        params: {
            navigationDisabled: true
        }
    },`

**Comment by alisherakb** [comment]
> Hi, to do that you need to wrap button.
> `MultiBar: { screen: () => null, navigationOptions: ({navigation}) => ({ tabBarIcon: () => ( <View style={{ flex: 1 }}> <Interactable.View snapPoints={[{x: 0, y: 0}]} onSnap={() => { }}> <MultiBarToggle navigation={navigation} actionSize={30} routes={[ { routeName: Routes.OtherScreen, color: '#FF8360', icon: ( <Icon name="rocket" color="#333333" size={15} /> ) }, { routeName: Routes.OtherScreen, color: '#E8E288', icon: ( <Icon name="dashboard" color="#333333" size={15} /> ) }, { routeName: Routes.OtherScreen, color: '#7DCE82', icon: ( <Icon name="gears" color="#333333" size={15} /> ) }, ]} icon={( <Icon name="plus" color="#FFFFFF" size={24} /> )} /> </Interactable.View> </View> ) }), params: { navigationDisabled: true } },`

Thanks, @alex-melnyk !!!

However, there are some strange behaviors on iOS/Android:
So in my case, it's not multibar, it's a button which navigates to draggable button's page (PopularPodcast) onPress or when dragged to certain snapPoint opens a new page(CurrentPodcast).

It works as expected if you are dragging from a page other than PopularPodcast on both iOS/Android.

Android behavior: 
1) The draggable button works ok until you drag to the first snap point and stucks there forever.
2) When you navigate to PopularPodcast page you cannot drag anymore. 

iOS behavior: 
1) When you navigate to PopularPodcast page you should try hard to start the drag. 

```
PopularPodcast: { 
      screen: PopularPodcast //draggable buttons page
      navigationOptions: () => ({
        tabBarIcon: ({ tintColor }) => (
            <Interactable.View
              initialPosition={{ x: 0, y: -35 }}
              snapPoints={[{ x: 0, y: -170 }, { x: 0, y: -35 }]}
              onSnap={() => {}} //navigates to CurrentPodcast page
            >
              <View
                style={{
                  width: 108,
                  height: 108,
                  borderRadius: 54
                }}
              />
            </Interactable.View>
        )
      })
    }
```

**Comment by alex-melnyk** [comment]
It looks like the effect related to the scrollview behind the tabbar

**Comment by alisherakb** [comment]
> It looks like the effect related to the scrollview behind the tabbar

@alex-melnyk Any workarounds? I would very appreciate your help!

**Comment by alisherakb** [comment]
@alex-melnyk Any thoughts?

**Comment by alex-melnyk** [comment]
Just disable scrolling on drag and activate after

**Comment by alisherakb** [comment]
> Just disable scrolling on drag and activate after

Do you mean disabling scrolling in TabBar options?

**Comment by alex-melnyk** [comment]
No, disable scrolling in the list behind tab bar, https://facebook.github.io/react-native/docs/scrollview#scrollenabled

**Comment by alisherakb** [comment]
> No, disable scrolling in the list behind tab bar, https://facebook.github.io/react-native/docs/scrollview#scrollenabled
> […](#)
> On Mar 12, 2019, at 11:51 PM, Alisher Akbarov ***@***.***> wrote: Just disable scrolling on drag and activate after Do you mean disabling scrolling in TabBar options? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I am using createBottomTabNavigator. Its config doesn't have scrollEnabled prop anywhere.
And I noticed that being in the draggable page, you can drag but if you start the drag from the upper side of this button.

Here is the code of BaseNavigator:
```
const TabsNavigator = createBottomTabNavigator(
  {
    Explore: {
      screen: Explore,
      navigationOptions: () => ({
        tabBarIcon: ({ tintColor }) => (
          <Svg width={24} height={24}>
            <Path
              d="M17.174 17.174L22 22l-4.826-4.826a8.889 8.889 0 1 1-12.57-12.57 8.889 8.889 0 0 1 12.57 12.57z"
              stroke={tintColor}
              strokeWidth={3}
              fill="none"
              fillRule="evenodd"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </Svg>
        )
      })
    },
    UsersCity: {
      screen: UsersCity,
      navigationOptions: () => ({
        tabBarIcon: ({ tintColor }) => (
          <View style={{ zIndex: 1 }}>
            <Interactable.View
              dragEnabled={true}
              initialPosition={{ x: 0, y: -10 }}
              snapPoints={[{ x: 0, y: -170 }, { x: 0, y: -10 }]}
              onSnap={() => null}
            >
              <Image
                source={{ uri: 'https://genesysx.io/NY.jpg' }}
                style={{
                  width: 108,
                  height: 108,
                  borderRadius: 54
                }}
              />
            </Interactable.View>
          </View>
        )
      })
    },
    Profile: {
      screen: Profile,
      navigationOptions: () => ({
        tabBarIcon: ({ tintColor }) => (
          <Svg width={24} height={26}>
            <Path
              d="M22 24.5H2c1.105-4.904 4.438-7.356 10-7.356s8.895 2.452 10 7.356zM12 12a5 5 0 1 1 0-10 5 5 0 0 1 0 10z"
              fill={tintColor}
              stroke={tintColor}
              strokeWidth={3}
              fillRule="evenodd"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </Svg>
        )
      })
    }
  },
  {
    tabBarOptions: {
      showLabel: false,
      lazy: false,
      activeTintColor: '#62A3FF',
      inactiveTintColor: '#BAC5D1',
      style: {
        backgroundColor: '#FFFFFF',
        borderTopColor: 'transparent',
        height: 56
      },
      tabStyle: {}
    }
  }
);
```

**Comment by alex-melnyk** [comment]
It isn't related to the tab bar at all, you need to disable scroll view on the screen, which above the tab bar, coz scroll view will intercept dragging.

**Comment by alisherakb** [comment]
> It isn't related to the tab bar at all, you need to disable scroll view on the screen, which above the tab bar, coz scroll view will intercept dragging.

Sorry for being annoying.
If you meant to disable scrolling via props within the draggable page, it doesn't work.
I've even tried to set pointerEvent to none to the corresponding container. And seems like the issue is not related with receiving touches on that page. 
Here is draggable page:
```
import React, { Component } from 'react';
import { SafeAreaView, Text } from 'react-native';

class UsersCity extends Component {
  render() {
    return (
      <SafeAreaView
        pointerEvents={'none'}
        style={{
          flex: 1,
          alignItems: 'center',
          backgroundColor: 'black',
          justifyContent: 'center'
        }}
      >
        <Text>Profile</Text>
      </SafeAreaView>
    );
  }
}

export { UsersCity };
```
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26904008/54597784-dcd74000-4a3f-11e9-804f-6439afd8ded0.gif)

**Comment by alisherakb** [comment]
@alex-melnyk 
I tried:
https://github.com/rome2rio/react-native-touch-through-view
Wrapped my page container with TouchThroughWrapper, and wrapped my button with TouchThroughView. Nothing helps... please provide your solution in more detail.
